import { Cat } from './cat';

export const CATEGORIES: Cat[] = [
  { id: 0, name: 'Alle Kategorien', show: true, class: "" },   
  { id: 6018, name: 'Bücher', show: true, class: "cat-books" },
  { id: 6014, name: 'Spiele', show: true, class: "cat-games" }, 
  { id: 6007, name: 'Produktivität', show: true, class: "cat-prod" },
  { id: 6008, name: 'Foto und Video', show: true, class: "cat-photo" },
  { id: 6003, name: 'Reisen', show: true, class: "cat-travel" },
  { id: 6004, name: 'Sport', show: true, class: "cat-sport" },
  { id: 6016, name: 'Unterhaltung', show: true, class: "cat-entertain" },
  { id: 6000, name: 'Wirtschaft', show: true, class: "cat-business" },
  { id: 6002, name: 'Dienstprogramme', show: true, class: "cat-utilities" }, 
  { id: 6009, name: 'Nachrichten', show: false, class: "cat-news" },
  { id: 6025, name: 'Sticker', show: false, class: "cat-sticker" },
  { id: 6024, name: 'Shopping', show: false, class: "cat-shop" },
  { id: 6010, name: 'Navigation', show: true, class: "cat-nav" },
  { id: 6011, name: 'Musik', show: true, class: "cat-music" },  
  { id: 6012, name: 'Lifestyle', show: true, class: "cat-lifestyle" },
  { id: 6013, name: 'Gesundheit und Fitness', show: true, class: "cat-health" },
  { id: 6005, name: 'Soziale Netze', show: true, class: "cat-social" },  
  { id: 6006, name: 'Nachschlagewerke', show: true, class: "cat-ref" },
  { id: 6015, name: 'Finanzen', show: true, class: "cat-finance" },  
  { id: 6017, name: 'Bildung', show: true, class: "cat-edu" },
  { id: 6001, name: 'Wetter', show: true, class: "cat-weather" },  
  { id: 6020, name: 'Medizin', show: true, class: "cat-medical" },
  { id: 6021, name: 'Zeitungen und Zeitschriften', show: false, class: "cat-magazine" },
  { id: 6022, name: 'Kataloge', show: false, class: "cat-catalogue" },
  { id: 6023, name: 'Essen und Trinken', show: true, class: "cat-food" },
  { id: 6026, name: 'Entwickler-Tools', show: false, class: "cat-devtools" },
  { id: 6027, name: 'Grafik und Design', show: false, class: "cat-graphic" },
  { id: 12001, name: 'Wirtschaft', show: true, class: "" },  
  { id: 12002, name: 'Entwickler-Tools', show: true, class: "" },
  { id: 12003, name: 'Bildung', show: true, class: "" },
  { id: 12004, name: 'Unterhaltung', show: true, class: "" },
  { id: 12005, name: 'Finanzen', show: true, class: "" },
  { id: 12006, name: 'Spiele', show: true, class: "" },
  { id: 12022, name: 'Grafik und Design', show: true, class: "" },
  { id: 12007, name: 'Gesundheit und Fitness', show: true, class: "" },
  { id: 12008, name: 'Lifestyle', show: true, class: "" },  
  { id: 12010, name: 'Medizin', show: true, class: "" },
  { id: 12011, name: 'Musik', show: true, class: "" },
  { id: 12012, name: 'Nachrichten', show: true, class: "" },
  { id: 12013, name: 'Fotografie', show: true, class: "" },
  { id: 12014, name: 'Produktivität', show: true, class: "" },
  { id: 12015, name: 'Nachschlagewerke', show: true, class: "" },
  { id: 12016, name: 'Soziale Netze', show: true, class: "" },
  { id: 12017, name: 'Sport', show: true, class: "" },
  { id: 12018, name: 'Reisen', show: true, class: "" },
  { id: 12019, name: 'Dienstprogramme', show: true, class: "" },
  { id: 12020, name: 'Video', show: true, class: "" },
  { id: 12021, name: 'Wetter', show: true, class: "" },
  ];

export const SUBCATEGORIES: Cat[] = [
  { id: 0, name: 'Alle', show: true, class: "" },
  { id:7001, name:"Action", show: true, class: "" },
  {id:7002, name:"Abenteuer", show: true, class: "" },
  {id:7003, name:"Spielhalle", show: true, class: "" },
  {id:7004, name:"Brettspiele", show: true, class: "" },
  {id:7005, name:"Kartenspiele", show: true, class: "" },
  {id:7006, name:"Casino", show: true, class: "" },
  {id:7007, name:"Würfelspiele", show: true, class: "" },
  {id:7008, name:"Bildung", show: true, class: "" },
  {id:7009, name:"Familie", show: true, class: "" },
  {id:7010, name:"Kinder", show: true, class: "" }, 
  {id:7011, name:"Musik", show: true, class: "" },
  {id:7012, name:"Puzzle", show: true, class: "" },
  {id:7013, name:"Rennsport", show: true, class: "" },
  {id:7014, name:"Rollenspiel", show: true, class: "" },
  {id:7015, name:"Simulation", show: true, class: "" },
  {id:7016, name:"Sport", show: true, class: "" },
  {id:7017, name:"Strategie", show: true, class: "" },
  {id:7018, name:"Quiz- und Denkspiele", show: true, class: "" },
  {id:7019, name:"Wortspiele", show: true, class: "" },
  // {id:12201, name:"Action", class: "" },
  // {id:12202, name:"Abenteuer", class: "" },
  // {id:12203, name:"Arcade-Spiele", class: "" },
  // {id:12204, name:"Brettspiele", class: "" },
  // {id:12205, name:"Kartenspiele", class: "" },
  // {id:12206, name:"Casino", class: "" },
  // {id:12207, name:"Würfelspiele", class: "" },
  // {id:12208, name:"Bildung", class: "" },
  // {id:12209, name:"Familie", class: "" },
  // {id:12210, name:"Kinder", class: "" },
  // {id:12211, name:"Musik", class: "" },
  // {id:12212, name:"Puzzle", class: "" },
  // {id:12213, name:"Rennsport", class: "" },
  // {id:12214, name:"Rollenspiel", class: "" },
  // {id:12215, name:"Simulation", class: "" },
  // {id:12216, name:"Sport", class: "" },
  // {id:12217, name:"Strategie", class: "" },
  // {id:12218, name:"Quiz- und Denkspiele", class: "" },
  // {id:12219, name:"Wortspiele", class: "" } 
];